# Generated by Django 5.2.1 on 2025-07-02 14:54

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('file', models.FileField(upload_to='datasets/')),
                ('rows_count', models.IntegerField(default=0)),
                ('processed', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['uploaded_at'], name='mining_data_uploade_e8e030_idx'), models.Index(fields=['processed'], name='mining_data_process_e728d8_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeologicalSurvey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('survey_id', models.CharField(max_length=100, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('survey_date', models.DateField()),
                ('author', models.CharField(max_length=255)),
                ('description', models.TextField(default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-survey_date'],
                'indexes': [models.Index(fields=['survey_id'], name='mining_geol_survey__c9318c_idx'), models.Index(fields=['survey_date'], name='mining_geol_survey__33d4a6_idx'), models.Index(fields=['location'], name='mining_geol_locatio_c07acc_idx')],
            },
        ),
        migrations.CreateModel(
            name='GeologicalFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature_type', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField()),
                ('description', models.TextField()),
                ('confidence_score', models.FloatField(default=1.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('name', models.CharField(blank=True, max_length=255)),
                ('gold_probability', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='mining.geologicalsurvey')),
            ],
        ),
        migrations.CreateModel(
            name='Miner',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unknown Miner', max_length=255)),
                ('license_number', models.CharField(default='UNKNOWN', max_length=100, unique=True)),
                ('contact_info', models.TextField(default='')),
                ('experience_years', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['license_number'], name='mining_mine_license_9d0f45_idx'), models.Index(fields=['created'], name='mining_mine_created_509f7c_idx')],
            },
        ),
        migrations.CreateModel(
            name='MineralDeposit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mineral_type', models.CharField(max_length=100)),
                ('concentration', models.FloatField(blank=True, null=True)),
                ('depth', models.FloatField(blank=True, null=True)),
                ('estimated_quantity', models.FloatField(blank=True, null=True)),
                ('extraction_difficulty', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mineral_deposits', to='mining.geologicalfeature')),
            ],
        ),
        migrations.CreateModel(
            name='PDFTextData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('extracted_text', models.TextField()),
                ('processed_text', models.TextField(blank=True, default='')),
                ('is_processed', models.BooleanField(default=False)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('text_file_path', models.CharField(blank=True, default='', max_length=500)),
                ('is_large_file', models.BooleanField(default=False)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.dataset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PredictionHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('elevation', models.FloatField(default=0)),
                ('soil_type', models.CharField(max_length=100)),
                ('geological_formation', models.CharField(max_length=100)),
                ('probability', models.FloatField()),
                ('confidence', models.FloatField()),
                ('mineral_type', models.CharField(default='gold', max_length=50)),
                ('depth_range', models.CharField(blank=True, default='', max_length=50)),
                ('extraction_difficulty', models.CharField(default='Medium', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['created_at'], name='mining_pred_created_76bd3d_idx'), models.Index(fields=['mineral_type'], name='mining_pred_mineral_8a65d1_idx'), models.Index(fields=['latitude', 'longitude'], name='mining_pred_latitud_9755c9_idx'), models.Index(fields=['soil_type'], name='mining_pred_soil_ty_ffa22e_idx'), models.Index(fields=['geological_formation'], name='mining_pred_geologi_08f9f4_idx')],
            },
        ),
        migrations.CreateModel(
            name='SoilAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('soil_type', models.CharField(max_length=100)),
                ('ph_level', models.FloatField(blank=True, null=True)),
                ('organic_matter', models.FloatField(blank=True, null=True)),
                ('mineral_content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='soil_analyses', to='mining.geologicalfeature')),
            ],
        ),
        migrations.CreateModel(
            name='TrainingRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accuracy', models.FloatField()),
                ('model_path', models.CharField(max_length=255)),
                ('training_date', models.DateTimeField(auto_now_add=True)),
                ('dataset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mining.dataset')),
            ],
            options={
                'ordering': ['-training_date'],
            },
        ),
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='uploaded', max_length=20)),
            ],
            options={
                'indexes': [models.Index(fields=['uploaded_at'], name='mining_uplo_uploade_7b6635_idx'), models.Index(fields=['status'], name='mining_uplo_status_f9cb57_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='geologicalfeature',
            index=models.Index(fields=['latitude', 'longitude'], name='mining_geol_latitud_a7fcee_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalfeature',
            index=models.Index(fields=['feature_type'], name='mining_geol_feature_3d9b9f_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalfeature',
            index=models.Index(fields=['confidence_score'], name='mining_geol_confide_58cb61_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalfeature',
            index=models.Index(fields=['gold_probability'], name='mining_geol_gold_pr_7ba20e_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalfeature',
            index=models.Index(fields=['created_at'], name='mining_geol_created_ce1a57_idx'),
        ),
        migrations.AddIndex(
            model_name='mineraldeposit',
            index=models.Index(fields=['mineral_type'], name='mining_mine_mineral_eb632d_idx'),
        ),
        migrations.AddIndex(
            model_name='mineraldeposit',
            index=models.Index(fields=['concentration'], name='mining_mine_concent_afeb7d_idx'),
        ),
        migrations.AddIndex(
            model_name='mineraldeposit',
            index=models.Index(fields=['extraction_difficulty'], name='mining_mine_extract_a59be8_idx'),
        ),
        migrations.AddIndex(
            model_name='mineraldeposit',
            index=models.Index(fields=['created_at'], name='mining_mine_created_8ca589_idx'),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['created_at'], name='mining_pdft_created_859bdf_idx'),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['is_processed'], name='mining_pdft_is_proc_a6e8ad_idx'),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['filename'], name='mining_pdft_filenam_592a91_idx'),
        ),
        migrations.AddIndex(
            model_name='soilanalysis',
            index=models.Index(fields=['soil_type'], name='mining_soil_soil_ty_cd0fb2_idx'),
        ),
        migrations.AddIndex(
            model_name='soilanalysis',
            index=models.Index(fields=['ph_level'], name='mining_soil_ph_leve_883cd0_idx'),
        ),
        migrations.AddIndex(
            model_name='soilanalysis',
            index=models.Index(fields=['created_at'], name='mining_soil_created_c19b08_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['training_date'], name='mining_trai_trainin_42e39b_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingrecord',
            index=models.Index(fields=['accuracy'], name='mining_trai_accurac_0af924_idx'),
        ),
    ]
