# Generated by Django 5.2.1 on 2025-07-04 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='content_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='file_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='file_size',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='original_filename',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['file_hash'], name='mining_pdft_file_ha_5c351d_idx'),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['content_hash'], name='mining_pdft_content_b70aec_idx'),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['original_filename'], name='mining_pdft_origina_02fa3c_idx'),
        ),
    ]
