# Generated by Django 5.2.1 on 2025-07-04 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0002_pdftextdata_content_hash_pdftextdata_file_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='status',
            field=models.CharField(default='uploaded', max_length=20),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['status'], name='mining_pdft_status_3eef00_idx'),
        ),
    ]
