# Generated by Django 5.2.1 on 2025-07-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0003_pdftextdata_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='file_path',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddIndex(
            model_name='pdftextdata',
            index=models.Index(fields=['file_path'], name='mining_pdft_file_pa_cc3918_idx'),
        ),
    ]
