# Generated by Django 5.2.1 on 2025-07-09 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0004_pdftextdata_file_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='needs_manual_review',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='quality_metrics',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
