# Generated by Django 5.2.1 on 2025-07-13 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0005_add_quality_metrics'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='document_type',
            field=models.CharField(choices=[('geological_survey', 'Geological Survey'), ('mining_map', 'Mining Map')], default='geological_survey', max_length=20),
        ),
    ]
