# Generated by Django 5.2.1 on 2025-07-13 18:24

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0006_pdftextdata_document_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploadedfile',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.CreateModel(
            name='GeologicalReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=500)),
                ('filename', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('document_type', models.CharField(default='geological_survey', max_length=50)),
                ('full_text', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('key_findings', models.JSONField(default=dict)),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('processing_status', models.CharField(default='processed', max_length=20)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('search_vector', models.TextField(blank=True)),
                ('tags', models.JSONField(default=list)),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='mining.pdftextdata')),
            ],
            options={
                'ordering': ['-processed_at'],
            },
        ),
        migrations.CreateModel(
            name='ReportIndex',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('indexed_text', models.TextField()),
                ('vector_embedding', models.JSONField(default=list)),
                ('word_frequencies', models.JSONField(default=dict)),
                ('entity_index', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indices', to='mining.geologicalreport')),
            ],
        ),
        migrations.CreateModel(
            name='ReportSection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('section_type', models.CharField(max_length=100)),
                ('section_title', models.CharField(blank=True, max_length=255)),
                ('section_order', models.IntegerField(default=0)),
                ('content', models.TextField()),
                ('summary', models.TextField(blank=True)),
                ('extracted_data', models.JSONField(default=dict)),
                ('keywords', models.JSONField(default=list)),
                ('entities', models.JSONField(default=list)),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='mining.geologicalreport')),
            ],
            options={
                'ordering': ['report', 'section_order'],
            },
        ),
        migrations.CreateModel(
            name='ReportQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_query', models.TextField()),
                ('query_type', models.CharField(max_length=50)),
                ('llm_response', models.TextField()),
                ('confidence_score', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processing_time', models.FloatField(default=0.0)),
                ('relevant_reports', models.ManyToManyField(related_name='queries', to='mining.geologicalreport')),
                ('relevant_sections', models.ManyToManyField(related_name='queries', to='mining.reportsection')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['title'], name='mining_geol_title_27458f_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['location'], name='mining_geol_locatio_1c6d2c_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['region'], name='mining_geol_region_29eac6_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['document_type'], name='mining_geol_documen_cd703f_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['processed_at'], name='mining_geol_process_cf614e_idx'),
        ),
        migrations.AddIndex(
            model_name='geologicalreport',
            index=models.Index(fields=['confidence_score'], name='mining_geol_confide_ecae1f_idx'),
        ),
        migrations.AddIndex(
            model_name='reportindex',
            index=models.Index(fields=['created_at'], name='mining_repo_created_c0a518_idx'),
        ),
        migrations.AddIndex(
            model_name='reportindex',
            index=models.Index(fields=['last_updated'], name='mining_repo_last_up_67de71_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['section_type'], name='mining_repo_section_def175_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['section_order'], name='mining_repo_section_b94780_idx'),
        ),
        migrations.AddIndex(
            model_name='reportsection',
            index=models.Index(fields=['keywords'], name='mining_repo_keyword_3f2b5e_idx'),
        ),
        migrations.AddIndex(
            model_name='reportquery',
            index=models.Index(fields=['query_type'], name='mining_repo_query_t_73d69c_idx'),
        ),
        migrations.AddIndex(
            model_name='reportquery',
            index=models.Index(fields=['created_at'], name='mining_repo_created_5ef903_idx'),
        ),
        migrations.AddIndex(
            model_name='reportquery',
            index=models.Index(fields=['confidence_score'], name='mining_repo_confide_369c44_idx'),
        ),
    ]
