# Generated by Django 5.2.1 on 2025-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0007_alter_uploadedfile_options_geologicalreport_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdftextdata',
            name='last_processing_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='last_processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='processing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdftextdata',
            name='processing_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdftextdata',
            name='status',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed'), ('unprocessed', 'Unprocessed'), ('retry_pending', 'Retry Pending')], default='uploaded', max_length=20),
        ),
    ]
