# Generated by Django 5.2.1 on 2025-08-06 16:42

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0008_pdftextdata_last_processing_attempt_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(max_length=255, unique=True)),
                ('user_agent', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('analysis_mode', models.CharField(default='smart', max_length=20)),
                ('documents_used', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-last_activity'],
                'indexes': [models.Index(fields=['session_id'], name='mining_conv_session_78ea44_idx'), models.Index(fields=['created_at'], name='mining_conv_created_27355f_idx'), models.Index(fields=['last_activity'], name='mining_conv_last_ac_deee12_idx'), models.Index(fields=['is_active'], name='mining_conv_is_acti_35324b_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('user', 'User'), ('assistant', 'Assistant'), ('system', 'System')], max_length=20)),
                ('content', models.TextField()),
                ('query_type', models.CharField(blank=True, max_length=50)),
                ('confidence_score', models.FloatField(default=0.0)),
                ('analysis_mode', models.CharField(default='smart', max_length=20)),
                ('documents_referenced', models.JSONField(default=list)),
                ('data_sources_used', models.JSONField(default=list)),
                ('response_time', models.FloatField(default=0.0)),
                ('tokens_used', models.IntegerField(default=0)),
                ('model_used', models.CharField(default='gpt-4o', max_length=50)),
                ('user_rating', models.IntegerField(blank=True, null=True)),
                ('user_feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='mining.conversationsession')),
            ],
            options={
                'ordering': ['session', 'created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='mining_conv_session_546469_idx'), models.Index(fields=['role'], name='mining_conv_role_7bc33c_idx'), models.Index(fields=['query_type'], name='mining_conv_query_t_8ce89f_idx'), models.Index(fields=['analysis_mode'], name='mining_conv_analysi_9a5f92_idx'), models.Index(fields=['user_rating'], name='mining_conv_user_ra_a0b25c_idx')],
            },
        ),
        migrations.CreateModel(
            name='ConversationAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('total_messages', models.IntegerField(default=0)),
                ('total_tokens', models.IntegerField(default=0)),
                ('average_response_time', models.FloatField(default=0.0)),
                ('query_types_distribution', models.JSONField(default=dict)),
                ('most_common_topics', models.JSONField(default=list)),
                ('user_satisfaction_score', models.FloatField(default=0.0)),
                ('documents_accessed', models.JSONField(default=list)),
                ('data_sources_utilized', models.JSONField(default=list)),
                ('user_expertise_level', models.CharField(default='beginner', max_length=20)),
                ('preferred_analysis_mode', models.CharField(default='smart', max_length=20)),
                ('improvement_suggestions', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to='mining.conversationsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session'], name='mining_conv_session_7c3a60_idx'), models.Index(fields=['user_satisfaction_score'], name='mining_conv_user_sa_2d16f4_idx'), models.Index(fields=['user_expertise_level'], name='mining_conv_user_ex_850a6a_idx'), models.Index(fields=['created_at'], name='mining_conv_created_2d6941_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserInteraction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('interaction_type', models.CharField(choices=[('query', 'Query'), ('feedback', 'Feedback'), ('mode_switch', 'Analysis Mode Switch'), ('document_upload', 'Document Upload'), ('error', 'Error'), ('success', 'Success')], max_length=50)),
                ('context_data', models.JSONField(default=dict)),
                ('user_preferences', models.JSONField(default=dict)),
                ('query_patterns', models.JSONField(default=list)),
                ('preferred_topics', models.JSONField(default=list)),
                ('response_satisfaction', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='mining.conversationsession')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session', 'created_at'], name='mining_user_session_912951_idx'), models.Index(fields=['interaction_type'], name='mining_user_interac_c5a568_idx'), models.Index(fields=['response_satisfaction'], name='mining_user_respons_d0ddd4_idx')],
            },
        ),
    ]
