# Generated by Django 5.2.1 on 2025-08-06 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0009_conversationsession_conversationmessage_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationAnalytics',
        ),
    ]
