# Generated by Django 5.2.1 on 2025-08-06 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0010_remove_analytics'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='conversationmessage',
            name='mining_conv_user_ra_a0b25c_idx',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='user_feedback',
        ),
        migrations.RemoveField(
            model_name='conversationmessage',
            name='user_rating',
        ),
    ]
