# Generated by Django 5.2.1 on 2025-10-31 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mining', '0011_remove_feedback_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelVersion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('version_number', models.CharField(max_length=50, unique=True)),
                ('model_path', models.CharField(max_length=500)),
                ('trained_at', models.DateTimeField(auto_now_add=True)),
                ('trained_by', models.CharField(blank=True, default='system', max_length=100)),
                ('accuracy', models.FloatField(blank=True, null=True)),
                ('f1_score', models.FloatField(blank=True, null=True)),
                ('training_samples', models.IntegerField(default=0)),
                ('validation_samples', models.IntegerField(default=0)),
                ('data_quality_score', models.FloatField(blank=True, null=True)),
                ('documents_used', models.IntegerField(default=0)),
                ('coordinates_generated', models.IntegerField(default=0)),
                ('model_type', models.CharField(default='RandomForest', max_length=50)),
                ('hyperparameters', models.JSONField(blank=True, null=True)),
                ('training_config', models.JSONField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_production', models.BooleanField(default=False)),
                ('deployment_status', models.CharField(choices=[('training', 'Training'), ('validated', 'Validated'), ('deployed', 'Deployed'), ('archived', 'Archived'), ('failed', 'Failed')], default='training', max_length=20)),
                ('description', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('predictions_count', models.IntegerField(default=0)),
                ('avg_prediction_time', models.FloatField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-trained_at'],
                'indexes': [models.Index(fields=['version_number'], name='mining_mode_version_89e648_idx'), models.Index(fields=['trained_at'], name='mining_mode_trained_6566ee_idx'), models.Index(fields=['is_active'], name='mining_mode_is_acti_da6e2f_idx'), models.Index(fields=['is_production'], name='mining_mode_is_prod_97de96_idx')],
            },
        ),
    ]
