# Generated by Django 5.2.1 on 2025-07-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='file_hash',
            field=models.CharField(blank=True, help_text='MD5 hash of the file for duplicate detection', max_length=64, null=True),
        ),
    ]
