# Generated by Django 5.2.1 on 2025-07-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocr', '0002_pdfupload_file_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='last_processing_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='last_processing_error',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='processing_attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pdfupload',
            name='processing_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='pdfupload',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('unprocessed', 'Unprocessed'), ('retry_pending', 'Retry Pending')], default='pending', max_length=20),
        ),
    ]
