# Generated by Django 5.2.1 on 2025-07-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pdfocr', '0003_pdfupload_last_processing_attempt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfupload',
            name='document_type',
            field=models.CharField(choices=[('geological_survey', 'Geological Survey'), ('mining_map', 'Mining Map')], default='geological_survey', max_length=50),
        ),
    ]
