"""
Django settings for goldMineAI project.

Generated by 'django-admin startproject' using Django 5.1.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""
import dj_database_url
import os
from pathlib import Path
from datetime import timedelta
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config('DEBUG', cast=bool)

ALLOWED_HOSTS = config('ALLOWED_HOSTS').split(',')

# Add localhost for local development
# if DEBUG:
#     ALLOWED_HOSTS.extend(['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'whitenoise.runserver_nostatic',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'mining.apps.MiningConfig',
    'rest_framework',
    'tailwind',
    'theme',
    # 'django_browser_reload',
    'corsheaders',
    'pdfocr',
]

TAILWIND_APP_NAME = 'theme'
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    #   'django_browser_reload.middleware.BrowserReloadMiddleware',
]

ROOT_URLCONF = 'goldMineAI.urls'

INTERNAL_IPS = ['127.0.0.1']

CORS_ORIGIN_ALLOW_ALL = True

# CORS_ALLOWED_ORIGINS = [
#     'http://localhost:3000',
#     'http://127.0.0.1:8000',
# ]

# Adobe PDF Services API settings
ADOBE_CLIENT_ID = config('ADOBE_CLIENT_ID')
ADOBE_CLIENT_SECRET = config('ADOBE_CLIENT_SECRET')

# OpenAI API key
OPENAI_API_KEY = config('OPENAI_API_KEY', default=None)

# Mapbox API key
MAPBOX_API_KEY = config('MAPBOX_API_KEY')

#Gold Price Tracker API key
GOLD_PRICE_TRACKER_API_KEY = config('GOLD_PRICE_TRACKER_API_KEY')

# Automated Training Configuration
AUTO_TRAIN_ON_PDF_UPLOAD = False  # Enable/disable automatic training when PDFs are uploaded
AUTO_TRAIN_MIN_FILES = 1  # Minimum number of unprocessed files before triggering training
AUTO_TRAIN_DELAY_SECONDS = 2  # Delay before starting training (to ensure file is saved)

# LLM Configuration
LLM_MODEL = "gpt-4o-mini"  # Default LLM model to use
LLM_TEMPERATURE = 0.1  # Temperature for LLM responses
LLM_MAX_TOKENS = 200000  # Maximum tokens for LLM responses

# Training Configuration
TRAINING_TEST_SIZE = 0.2  # Test set size for model training
TRAINING_RANDOM_STATE = 42  # Random state for reproducible results
TRAINING_CV_FOLDS = 5  # Number of cross-validation folds

# Model Storage
MODEL_STORAGE_PATH = "mining/models/"  # Path to store trained models
DATASET_STORAGE_PATH = "media/datasets/"

# File upload limits
FILE_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB
DATA_UPLOAD_MAX_MEMORY_SIZE = 100 * 1024 * 1024  # 100MB


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'goldMineAI.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

#DATABASES["default"] = dj_database_url.parse(config('DATABASE_URL'))

#DATABASES["default"] = dj_database_url.parse("postgresql://goldminedb_user:ZS0NjJM75bxbQNiOHzowxUj6SMukuDEA@dpg-cvo6t86mcj7s73fukba0-a.oregon-postgres.render.com/goldminedb")

# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Django REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
        'rest_framework.renderers.BrowsableAPIRenderer',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

MEDIA_URL = 'media/'

MEDIA_ROOT = BASE_DIR / 'media'

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles' 

#STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"

# Cloud Storage Configuration (for production)
# Uncomment and configure these settings for cloud storage
# AWS_ACCESS_KEY_ID = config('AWS_ACCESS_KEY_ID')
# AWS_SECRET_ACCESS_KEY = config('AWS_SECRET_ACCESS_KEY')
# AWS_STORAGE_BUCKET_NAME = config('AWS_STORAGE_BUCKET_NAME')
# AWS_S3_REGION_NAME = config('AWS_S3_REGION_NAME')
# AWS_S3_FILE_OVERWRITE = False
# AWS_DEFAULT_ACL = None
# AWS_S3_VERIFY = True
# DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'


# For local development, files are stored in MEDIA_ROOT
# For production, configure cloud storage above

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
